"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {useTranslations} from "next-intl";import {createClient} from "@/lib/supabase/client";
type D={id:string;external_id:string;type:string;village:string;district:string;status:string;last_seen:string|null};type T={id:string;device_id:string;ts:string;body_temp_c:number|null;rumination_min:number|null;activity:number|null;milk_yield_kg:number|null;env_temp_c:number|null;battery_pct:number|null};type A={id:string;device_id:string;ts:string;severity:string;concurrent_devices:number;report_id:string|null;deviations:Record<string,number>};type R={id:string;created_at:string;status:string;sick_count:number;village:string|null};
function Spark({values,color}:{values:number[];color:string}){const pts=values.length<2?"0,38 100,38":values.map((v,i)=>`${i*100/(values.length-1)},${70-(v-Math.min(...values))*55/Math.max(.01,Math.max(...values)-Math.min(...values))}`).join(" ");return <svg viewBox="0 0 100 76" className="h-20 w-full" preserveAspectRatio="none"><path d="M0 70H100" stroke="#e6ddcd"/><polyline points={pts} fill="none" stroke={color} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg>}
export function IoTDashboard({initialDevices,initialTelemetry,initialAnomalies,initialReports}:{initialDevices:D[];initialTelemetry:T[];initialAnomalies:A[];initialReports:R[]}){const t=useTranslations("iot"),[devices]=useState(initialDevices),[telemetry,setTelemetry]=useState(initialTelemetry),[anomalies,setAnomalies]=useState(initialAnomalies),[reports,setReports]=useState(initialReports),[busy,setBusy]=useState(false),[error,setError]=useState("");const db=useMemo(()=>createClient(),[]);
 useEffect(()=>{const c=db.channel("iot-live").on("postgres_changes",{event:"INSERT",schema:"public",table:"telemetry"},p=>setTelemetry(x=>[p.new as T,...x].slice(0,120))).on("postgres_changes",{event:"INSERT",schema:"public",table:"iot_anomalies"},p=>setAnomalies(x=>[p.new as A,...x])).on("postgres_changes",{event:"INSERT",schema:"public",table:"reports",filter:"source=eq.iot"},p=>setReports(x=>[p.new as R,...x])).subscribe();return()=>{db.removeChannel(c)}},[db]);
 async function act(action:"run"|"reset"){setBusy(true);setError("");try{const r=await fetch("/api/iot/simulate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const j=await r.json();if(!r.ok)throw new Error(j.error);if(action==="reset"){setTelemetry([]);setAnomalies([]);setReports([])}else location.reload()}catch(e){setError(e instanceof Error?e.message:t("error"))}finally{setBusy(false)}}
 const chronological=[...telemetry].sort((a,b)=>a.ts.localeCompare(b.ts));return <div className="mt-6 space-y-5"><div className="rounded-3xl border border-line bg-card p-5 shadow-[var(--shadow-card)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-serif text-xl font-semibold">{t("farmerMeaningTitle")}</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-mut">{t("farmerMeaningBody")}</p></div><Link href="/dashboard/report" className="shrink-0 rounded-full bg-accent px-4 py-2.5 text-center text-sm font-bold text-white">{t("manualReport")}</Link></div><div className="mt-4 rounded-2xl bg-accent-soft p-3 text-xs leading-relaxed text-ink-2">{t("privacyNote")}</div></div>
  <div className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-line-2 p-5"><div><h2 className="font-serif text-xl font-semibold">{t("simTitle")}</h2><p className="mt-1 max-w-2xl text-xs text-mut">{t("simHint")}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>act("reset")} className="rounded-full border border-line bg-card px-4 py-2 text-sm font-semibold disabled:opacity-50">{t("reset")}</button><button disabled={busy} onClick={()=>act("run")} className="rounded-full bg-accent px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?t("running"):t("run")}</button></div></div>{error&&<p className="m-4 rounded-xl bg-[#F9E3DB] p-3 text-sm text-[#A8431F]">{error}</p>}<div className="grid gap-3 p-4 sm:grid-cols-3">{devices.map(d=><div className="rounded-2xl border border-line p-4" key={d.id}><div className="flex justify-between"><b>{d.external_id}</b><span className="h-2.5 w-2.5 rounded-full bg-[#71834b]"/></div><p className="mt-1 text-xs text-mut">{d.type.replace("_"," ")} · {d.village}</p><p className="mt-3 text-[11px] text-mut">{d.last_seen?t("lastSeen",{date:new Date(d.last_seen).toLocaleString()}):t("waiting")}</p></div>)}</div></div>
  <div className="grid gap-4 md:grid-cols-2">{[["temperature","body_temp_c","#A8431F"],["rumination","rumination_min","#71834b"],["activity","activity","#B98523"],["milk","milk_yield_kg","#486e78"]].map(([label,key,color])=><div className="card p-4" key={key}><div className="flex justify-between"><b className="text-sm">{t(label)}</b><span className="text-[11px] text-mut">{t("live")}</span></div><Spark values={chronological.map(x=>Number(x[key as keyof T])).filter(Number.isFinite)} color={color}/></div>)}</div>
  <div className="grid gap-5 lg:grid-cols-2"><div className="card p-5"><h2 className="font-serif text-xl font-semibold">{t("detections")}</h2>{anomalies.length?<div className="mt-3 space-y-2">{anomalies.slice(0,8).map(a=><div key={a.id} className="rounded-xl border border-line p-3"><div className="flex justify-between"><b className="text-sm">{t("anomaly")}</b><span className="chip text-[10px]">{a.concurrent_devices} {t("animals")}</span></div><p className="mt-1 text-xs text-mut">{t("deviation",{temp:Number(a.deviations?.body_temp_c??0).toFixed(1),rum:Math.abs(Number(a.deviations?.rumination_pct??0)).toFixed(0)})}</p>{a.report_id&&<p className="mt-2 text-xs font-semibold text-accent">{t("reportCreated")}</p>}</div>)}</div>:<p className="mt-5 text-sm text-mut">{t("noDetections")}</p>}</div><div className="card p-5"><h2 className="font-serif text-xl font-semibold">{t("autoReports")}</h2>{reports.length?<div className="mt-3 space-y-2">{reports.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border border-line p-3"><div><b className="text-sm">{r.village}</b><p className="text-xs text-mut">{r.sick_count} {t("animalsAffected")}</p></div><span className="chip text-[10px]">{r.status}</span></div>)}</div>:<p className="mt-5 text-sm text-mut">{t("noReports")}</p>}</div></div>
  <div className="rounded-2xl border border-gold bg-gold-soft p-4 text-xs leading-relaxed">{t("disclaimer")}</div>
 </div>}
